### ISSUE TITLE
res: testnet genesis alloc

### ISSUE THREAD

**Issue by soc1c** [dothereum/dothereum#21]
preallocate accouts for the dothereum gamma testnet.

fetch addresses from
- [x] polkadot presale / kusama claims contract
- [x] edgeware lockdrop
- [ ] kusama accounts state snapshot

create fixed allocation of 10 test-xth for each account. mainly done in #35 by @soc1c. 

leaving this open for people manually signalling interest to post their dothereum accounts.

**Comment by soc1c** [comment]
pre-allocated 5113 addresses in #35

**Comment by soc1c** [comment]
from discord:

- 319sHfb2a22MyzefyxVzfEghRgsZ5E2J6DVETpu2ab1MCJiZ
- 35usV1PsmPgmQbUmtxxuDLV2fN3tUp54qNLmSHhC1ENjBNcK
- 2zzcXBxSvY14fm3PyU2a55r4SiS3Gd2vipHUd8qskebEeXYG

**Comment by soc1c** [comment]
Instructions: https://github.com/dothereum/dothereum/wiki/Allocation

**Comment by roninkaizen** [comment]
31esZMfPAEpiD7yLMnXZirYUgQ8wY97H4JPNmgDt9zH4J4Qw,
yours ronin-kaizen

**Comment by soc1c** [comment]
33Ti1MXrBhBh2G6AexBsm22mYt4i5N8755zTyL1VQm6V237w

**Comment by soc1c** [comment]
Done
