### ISSUE TITLE
openssl libs are needed

### ISSUE THREAD

**Issue by roninkaizen** [dothereum/dothereum#28]
due to my gist
https://gist.github.com/roninkaizen/c0ac19c2db10e11f0709e04c12089a54#file-not-build-missing-ssl-something

but citing from the dump
"Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora." it could work,
about to test it now, reporting later.

**Comment by sofim** [comment]
Right, these are the deps:

```bash
    sudo apt install build-essential cmake pkg-config libssl-dev openssl git clang libclang-dev
```

Needs docs
