### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by roninkaizen** [dothereum/dothereum#45]
taken from one of my consoles-
tried it twice-
everything there, another dothereum instance (alpha is running on the same system)
here we go with the compile error itself:
The following warnings were emitted during compilation:

warning: Could not find `.git/HEAD` searching from `/home/ubuntu/dothereum-beta` upwards!

error: could not compile `dothereum`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name dothereum src/main.rs --color always --crate-type bin --emit=dep-inf                                                                                                  o,link -C opt-level=3 -C metadata=6c90647021f78122 -C extra-filename=-6c90647021f78122 --out-dir /home/ubuntu/dothereum-beta/target/release                                                                                                  /deps -L dependency=/home/ubuntu/dothereum-beta/target/release/deps --extern ctrlc=/home/ubuntu/dothereum-beta/target/release/deps/libctrlc                                                                                                  -3d5534c641f64ca2.rlib --extern derive_more=/home/ubuntu/dothereum-beta/target/release/deps/libderive_more-408a33b2d6024c4a.so --extern dot                                                                                                  hereum_runtime=/home/ubuntu/dothereum-beta/target/release/deps/libdothereum_runtime-da569d879bfa0c75.rlib --extern exit_future=/home/ubuntu                                                                                                  /dothereum-beta/target/release/deps/libexit_future-07e8af0795b276c6.rlib --extern futures=/home/ubuntu/dothereum-beta/target/release/deps/l                                                                                                  ibfutures-d6d90b26a1db9345.rlib --extern log=/home/ubuntu/dothereum-beta/target/release/deps/liblog-5f075c2f94d34499.rlib --extern codec=/h                                                                                                  ome/ubuntu/dothereum-beta/target/release/deps/libparity_scale_codec-0bb9a1214dabb76e.rlib --extern parking_lot=/home/ubuntu/dothereum-beta/                                                                                                  target/release/deps/libparking_lot-d602a696abfef0e9.rlib --extern rust_embed=/home/ubuntu/dothereum-beta/target/release/deps/librust_embed-                                                                                                  494ee284627a9a24.rlib --extern sr_io=/home/ubuntu/dothereum-beta/target/release/deps/libsr_io-ea276dcccf693796.rlib --extern sr_primitives=                                                                                                  /home/ubuntu/dothereum-beta/target/release/deps/libsr_primitives-80a036f514daa629.rlib --extern basic_authorship=/home/ubuntu/dothereum-bet                                                                                                  a/target/release/deps/libsubstrate_basic_authorship-6f208440859e446d.rlib --extern substrate_cli=/home/ubuntu/dothereum-beta/target/release                                                                                                  /deps/libsubstrate_cli-a38c621f03892624.rlib --extern substrate_client=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_client-                                                                                                  df0b6bcd9733e997.rlib --extern aura=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_consensus_aura-4f23e24d0560d53f.rlib --ext                                                                                                  ern aura_primitives=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_consensus_aura_primitives-c440269eecb545d9.rlib --extern s                                                                                                  ubstrate_executor=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_executor-6226fe4c02a5cd21.rlib --extern grandpa=/home/ubuntu                                                                                                  /dothereum-beta/target/release/deps/libsubstrate_finality_grandpa-37596a5547e57b51.rlib --extern grandpa_primitives=/home/ubuntu/dothereum-                                                                                                  beta/target/release/deps/libsubstrate_finality_grandpa_primitives-c7a22f63b99f5c0c.rlib --extern inherents=/home/ubuntu/dothereum-beta/targ                                                                                                  et/release/deps/libsubstrate_inherents-da125abd8a45c95a.rlib --extern network=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_                                                                                                  network-d089201097c2a7f2.rlib --extern primitives=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_primitives-8e1ee94e4152c446.                                                                                                  rlib --extern substrate_service=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_service-d1d0a97d5ee681e7.rlib --extern transac                                                                                                  tion_pool=/home/ubuntu/dothereum-beta/target/release/deps/libsubstrate_transaction_pool-8019c5164cc61acc.rlib --extern tokio=/home/ubuntu/d                                                                                                  othereum-beta/target/release/deps/libtokio-8cf7cb0cd4d19c3f.rlib --extern trie_root=/home/ubuntu/dothereum-beta/target/release/deps/libtrie                                                                                                  _root-033a51001741d7fc.rlib -L native=/home/ubuntu/dothereum-beta/target/release/build/clear_on_drop-0acf4c96f8865ac7/out -L native=/home/u                                                                                                  buntu/dothereum-beta/target/release/build/backtrace-sys-8b57d23880f19999/out -L native=/home/ubuntu/dothereum-beta/target/release/build/rin                                                                                                  g-c82fb81a182685a5/out -L native=/usr/lib/x86_64-linux-gnu -L native=/home/ubuntu/dothereum-beta/target/release/build/librocksdb-sys-52e852                                                                                                  758c6495e4/out -L native=/home/ubuntu/dothereum-beta/target/release/build/librocksdb-sys-52e852758c6495e4/out -L native=/home/ubuntu/dother                                                                                                  eum-beta/target/release/build/librocksdb-sys-52e852758c6495e4/out -L native=/home/ubuntu/dothereum-beta/target/release/build/librocksdb-sys                                                                                                  -52e852758c6495e4/out -L native=/home/ubuntu/dothereum-beta/target/release/build/librocksdb-sys-52e852758c6495e4/out -L native=/home/ubuntu                                                                                                  /dothereum-beta/target/release/build/librocksdb-sys-52e852758c6495e4/out` (signal: 9, SIGKILL: kill)

**Comment by roninkaizen** [comment]
and yes,
for sure i let the scripts/init.sh run before trying to compile (:

**Comment by soc1c** [comment]
> (signal: 9, SIGKILL: kill)

Your node is out of memory :)

You can increase the VM size or create a SWAP partition.

**Comment by roninkaizen** [comment]
thx- will do

**Comment by roninkaizen** [comment]
and yes, it is really early in the morning (:
did not see the mem-exhaust on first sight
